version: '3'
services:
  dc-nginx:
    container_name: "dc-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - dc-app
    ports:
      - 80:80
    volumes:
      - ./:/src

  dc-app:
    container_name: "dc-app"
    build:
      context: ./docker/php
    depends_on:
      - dc-mysql
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  dc-mysql:
    image: mysql:8.0.37
    command: --max_allowed_packet=32505856
    container_name: "dc-mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dc
    ports:
      - 3306:3306

  dc-redis:
    image: redis:alpine
    container_name: "dc-redis"
    ports:
      - 16379:6379
